### ISSUE TITLE
惊喜

### ISSUE THREAD

**Issue by peter100u** [CurrentIndex/flutter_codemirror#1]
找了二天flutter代码编辑插件，还是你这个好，厉害厉害，大佬要坚持更新啊，好好维护

**Comment by peter100u** [comment]
我又来了，辛苦升级下 flutter_webview呢 
Because every version of flutter_codemirror depends on webview_flutter ^3.0.4 and every version of utils from path depends on webview_flutter 4.0.2, flutter_codemirror is incompatible with utils from path.
So, because shader_toy depends on both utils from path and flutter_codemirror 1.0.0+1, version solving failed.

**Comment by BahelanBaishan** [comment]
> 找了二天flutter代码编辑插件，还是你这个好，厉害厉害，大佬要坚持更新啊，好好维护

谢谢，两月底会发布新版本，增加大量功能，解决部分bug

**Comment by BahelanBaishan** [comment]
> 我又来了，辛苦升级下 flutter_webview呢 
> Because every version of flutter_codemirror depends on webview_flutter ^3.0.4 and every version of utils from path depends on webview_flutter 4.0.2, flutter_codemirror is incompatible with utils from path.
> So, because shader_toy depends on both utils from path and flutter_codemirror 1.0.0+1, version solving failed.

下个版本更新

**Comment by peter100u** [comment]
好好维护，前景无量啊， readme可以优化些，这样有利于传播

**Comment by peter100u** [comment]
大佬，等你的更新呢
